### ISSUE TITLE
Cutthroat mission is too hard

### ISSUE THREAD

**Issue by Derpalus** [TheCondor07/Starcraft2ArchipelagoData#3]
Map: ap_thorner02.SC2Map

The AI collects money too quickly.

After playing the mission once on brutal noticing a suspiciously high amount of SCVs at the enemy bases (and even an SCV going straight through my base trying to reinforce another base) my theory was that the AI was building SCVs (which I don't think it's supposed to do on this mission).

Adding a trigger that counted the number of enemy SCVs confirmed this.

I suspect something in the Archipelago scripts by mistake start the "standard" AI behaviour of building SCVs, but I'm not skilled enough to know for sure. It might be this action that activates the AI:
![bild](https://user-images.githubusercontent.com/17323868/183523445-e912a65c-6382-41af-86ef-b9635872f19a.png)

**Comment by Derpalus** [comment]
I tried disabling that action, but it didn't do any difference.
I did manage to win on brutal though, you just have to be super aggressive and take down the enemy command centers within minutes. Without a fast unit such as the vulture however it's probably pretty hard.

**Comment by Berserker66** [comment]
I believe https://github.com/TheCondor07/Starcraft2ArchipelagoData/releases/tag/1.13 fixed this, so this should probably be closed?

**Comment by TheCondor07** [comment]
Yes, closing.
